### ISSUE TITLE
New cache eviction method renders the game unplayable

### ISSUE THREAD

**Issue by RobotHanzo** [nea89o/veloxcaelo#1]
The game is barely playable (i.e. Around 5-10 fps) after the new cache eviction change
The tick event is being overloaded
Perhaps a concurrent eviction is needed?
![image](https://github.com/nea89o/veloxcaelo/assets/36107150/fe9130c0-aaa3-4b16-aec7-ef2911d750f1)

Spark Profile: https://spark.lucko.me/r0gVmtfUXU

**Comment by lineargraph** [comment]
I mean i can make use of a reference queue but i also dont really see this behaviour myself. Are you sure you are on the latest version? Can you check the output of `/velox opticache`.

**Comment by RobotHanzo** [comment]
Yes I'm on 1.0.2
I also observed that this behavior starts happening after 1~2 minutes after joining a skyblock lobby

First time running
![image](https://github.com/nea89o/veloxcaelo/assets/36107150/441f1652-e0b3-409d-8a83-f973698a383b)

After some while (fps dropped to 20)
![image](https://github.com/nea89o/veloxcaelo/assets/36107150/7c1d85d4-97f5-4636-b15f-8275d2de0f8d)

**Comment by lineargraph** [comment]
This looks to me like it just never ever actually evicts anything, which was a bug with an older version. Or maybe another one of your mods is keeping a reference to these item stacks alive. I suppose i can make use of a reference queue which will remove the cpu load here, but if those item stacks are being kept alive by another mod then that can cause issues as well.

**Comment by RobotHanzo** [comment]
I'll try to check for memory leaks, thanks

**Comment by lineargraph** [comment]
I pushed a reference queue strategy onto the master branch, feel free to check that one out to see if it performs any better. I can send you a built jar on discord.

**Comment by RobotHanzo** [comment]
First run
![image](https://github.com/nea89o/veloxcaelo/assets/36107150/a57c9860-231e-4ecb-b6a1-5fab206d218e)
Second run after an hour
![image](https://github.com/nea89o/veloxcaelo/assets/36107150/0c628e2b-f5da-49b9-9782-622c22e6e8c8)

The new version works pretty well, interesting to see the cache size dropped a lot as well

**Comment by lineargraph** [comment]
This is still broken, but at least it doesnt spin your CPU anymore. I havent really ever seen the cache size grow over about 10000. There is definitely something else going on that holds references to some item stacks. But at least with a reference queue that wont cost you extra CPU, just extra RAM.

**Comment by RobotHanzo** [comment]
Is there a way to check which mod is holding the reference

**Comment by lineargraph** [comment]
Sadly not. I recently worked on a heap dump analyzer which would solve that question, but i ended up not being able to complete that project due to time problems. I might pick it back up again.

**Comment by lineargraph** [comment]
Going to close this since this seems to be done by an unrelated mod and new versions should no longer cause lag if other mods keep references alive.
